#!/bin/bash
jupyter labextension install @jupyter-widgets/jupyterlab-manager \
                             jupyter-matplotlib \
                             @pyviz/jupyterlab_pyviz \
                             jupyter-leaflet \
                             dask-labextension

#EOF
