#!/bin/bash
jupyter serverextension enable --py jupyter_server_proxy --sys-prefix
jupyter labextension install @jupyter-widgets/jupyterlab-manager \
                             @pyviz/jupyterlab_pyviz \
                             jupyter-leaflet \
                             dask-labextension

# import the workspace configuration for the default workspace
jupyter lab workspaces import binder/jupyterlab-workspace.json

#EOF
